#!/data/data/com.termux/files/usr/bin/bash

rm -rf /data/data/com.termux/files/usr/bin/start-x11

wget https://raw.githubusercontent.com/IamShivanshCoder/termux-rice/refs/heads/main/start-x11 -O /data/data/com.termux/files/usr/bin/start-x11
termux-reload-settings

